"""Added genre column to games

Revision ID: f2eda9d49f04
Revises: eaaa29070276
Create Date: 2025-02-10 14:14:06.286379

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f2eda9d49f04'
down_revision: Union[str, None] = 'eaaa29070276'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('games', sa.Column('genre', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('games', 'genre')
    # ### end Alembic commands ###
